[tools]
aws-cli = "latest"
bun = "latest"
deno = "latest"
flutter = "latest"
go = "latest"
helm = "latest"
just = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
node = "latest"
pnpm = "latest"
pulumi = "latest"
python = "latest"
terraform = "latest"
uv = "latest"
zellij = "latest"
